resolver: lts-13.26
packages:
- .
nix:
    enable: false
extra-deps:
- git: https://github.com/well-typed/optics.git
  commit: a29144984843e67215256c63155df7f201983d63
  subdirs:
   - optics-core
   - optics-th
